export const PRIORITY_1_0 = ["/"]

export const PRIORITY_0_9 = [
  "/about-us",
  "/services",
  "/services/chiropractic",
  "/services/massage",
  "/services/car-truck-accident-care",
  "/new-folks",
  "/contact-us",
  "/schedule",
  "/booking",
  "/testimonials",
  "/blog",
]

export const PRIORITY_0_8 = [
  "/about-us/meet-dr-brad",
  "/about-us/meet-dr-brad/dr-brads-full-story",
  "/about-us/meet-austin",
  "/about-us/meet-bert",
  "/about-us/meet-jess",
  "/about-us/meet-kathryn",
  "/new-folks/first-visit",
  "/new-folks/our-vision",
  "/new-folks/np-schedule",
  "/what-is-a-subluxation",
  "/nerve-chart",
  "/degeneration",
  "/chiropractic-history",
  "/chiropractic-research",
  "/triune-of-care",
  "/common-conditions",
  "/common-conditions/amyotrophic-lateral-sclerosis-als",
  "/area-we-serve",
  "/neuropathy",
]

export const PRIORITY_0_7 = [
  "/resources",
  "/resources/all-about-nutrition",
  "/resources/all-about-spinal-hygiene",
  "/resources/improve-your-sha-score",
  "/resources/essential-nutrients-supplements",
  "/resources/videos",
  "/resources/videos/spinal-hygiene-videos",
  "/resources/videos/workshop-videos",
  "/resources/videos/workshop-videos-of-the-past",
  "/resources/videos/promo-videos",
  "/resources/videos/humorous-promo-videos-of-the-past",
  "/resources/videos/other-videos",
  "/resources/calendar",
  "/resources/get-notified",
  "/resources/order-supplements",
  "/resources/adjusting-hours",
  "/helpful-stretches",
  "/spinal-hygiene-video",
  "/use-your-head-video",
  "/backpack-analogy",
  "/30-second-spinal-hygiene-report-card",
  "/traction",
  "/thoracic-roller",
  "/6-way-strap",
  "/over-the-door-traction",
  "/mobility-disk-for-lower-back",
]

export const PRIORITY_0_6 = [
  "/chiropractor-albuquerque-nm",
  "/chiropractor-bernalillo-nm",
  "/chiropractor-corrales-nm",
  "/chiropractor-casa-colorada-nm",
  "/chiropractor-chilili-nm",
  "/chiropractor-ponderosa-nm",
  "/chiropractic-los-lunas-nm",
  "/chiropractic-placitas-nm",
  "/chiropractic-belen-nm",
  "/chiropractic-edgewood-nm",
  "/chiropractic-moriarty-nm",
  "/chiropractic-cedar-crest-nm",
  "/chiropractic-north-valley",
  "/chiropractic-south-valley-nm",
  "/chiropractic-tijeras-nm",
  "/chiropractic-bosque-farms-nm",
  "/chiropractic-canoncito-nm",
  "/chiropractic-cochiti-lake-nm",
  "/chiropractic-cochiti-pueblo-nm",
  "/chiropractic-el-cerro-mission-nm",
  "/chiropractic-el-llanito-nm",
  "/chiropractic-golden-nm",
  "/chiropractic-jarales-nm",
  "/chiropractic-jemez-pueblo-nm",
  "/chiropractic-los-ranchos-de-albuquerque",
  "/chiropractic-meadow-lake-nm",
  "/chiropractic-pena-blanca-nm",
  "/chiropractic-peralta-nm",
  "/chiropractic-san-felipe-pueblo-nm",
  "/chiropractic-san-ysidro-nm",
  "/chiropractic-sandia-park-nm",
  "/chiropractic-santa-ana-pueblo-nm",
  "/chiropractic-tome-nm",
  "/chiropractic-zia-pueblo-nm",
]

export const STATIC_PUBLIC_PATHS = [
  ...PRIORITY_1_0,
  ...PRIORITY_0_9,
  ...PRIORITY_0_8,
  ...PRIORITY_0_7,
  ...PRIORITY_0_6,
]

export const RESERVED_PROGRAMMATIC_SLUGS = new Set<string>([
  "chiropractor-albuquerque-nm",
  "chiropractor-bernalillo-nm",
  "chiropractor-casa-colorada-nm",
  "chiropractor-chilili-nm",
  "chiropractor-corrales-nm",
  "chiropractor-ponderosa-nm",
])

export const WEEKLY_PATHS = new Set(["/", "/blog", "/schedule"])
